execute as @s if predicate copperrust:inventory_0_item_frame run item modify entity @s inventory.0 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_1_item_frame run item modify entity @s inventory.1 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_2_item_frame run item modify entity @s inventory.2 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_3_item_frame run item modify entity @s inventory.3 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_4_item_frame run item modify entity @s inventory.4 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_5_item_frame run item modify entity @s inventory.5 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_6_item_frame run item modify entity @s inventory.6 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_7_item_frame run item modify entity @s inventory.7 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_8_item_frame run item modify entity @s inventory.8 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_9_item_frame run item modify entity @s inventory.9 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_10_item_frame run item modify entity @s inventory.10 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_11_item_frame run item modify entity @s inventory.11 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_12_item_frame run item modify entity @s inventory.12 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_13_item_frame run item modify entity @s inventory.13 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_14_item_frame run item modify entity @s inventory.14 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_15_item_frame run item modify entity @s inventory.15 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_16_item_frame run item modify entity @s inventory.16 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_17_item_frame run item modify entity @s inventory.17 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_18_item_frame run item modify entity @s inventory.18 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_19_item_frame run item modify entity @s inventory.19 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_20_item_frame run item modify entity @s inventory.20 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_21_item_frame run item modify entity @s inventory.21 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_22_item_frame run item modify entity @s inventory.22 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_23_item_frame run item modify entity @s inventory.23 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_24_item_frame run item modify entity @s inventory.24 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_25_item_frame run item modify entity @s inventory.25 copperrust:item_frame_to_bat_egg
execute as @s if predicate copperrust:inventory_26_item_frame run item modify entity @s inventory.26 copperrust:item_frame_to_bat_egg